services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smartmoney
      POSTGRES_USER: smf
      POSTGRES_PASSWORD: smf_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  indexer:
    build: ./services/indexer
    depends_on:
      - postgres
    restart: always
    environment:
      BASE_RPC_URL: https://base-mainnet.infura.io/v3/bec07fd60dd44de399e3e68ffc508867

  analytics:
    build: ./services/analytics
    depends_on:
      - postgres
    restart: always

  alerts:
    build: ./services/alerts
    depends_on:
      - postgres
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
  daily:
    build: ./services/daily
    depends_on:
      - postgres
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    restart: always

volumes:
  pgdata:
